project:
  type: website
  output-dir: docs
  resources:
    - downloads/**

website:
  title: "HOPE Thoracic repository"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: downloads/index.qmd
        text: Downloads
      - about.qmd


format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: visual

