project:
  type: website
  output-dir: docs
  resources:
    - downloads/**

website:
  title: "HOPE Thoracic repository"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: downloads/index.qmd
        text: Downloads
      - about.qmd
      - href: faq.qmd
        text: FAQ
  page-footer:
    left: |
      © 2025 HOPE Thoracic
    right: |
      Built with [Quarto](https://quarto.org) and pkgdown-style theme


format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: visual

